/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-04-03 06:07:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.웨딩;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<main id=\"main\">\r\n");
      out.write("    <section id=\"section1\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"slide-container\">\r\n");
      out.write("                <div class=\"slide-view\">\r\n");
      out.write("                    <ul class=\"slide-wrap\">\r\n");
      out.write("                        <li class=\"slide slide1\"></li>\r\n");
      out.write("                        <li class=\"slide slide2\"></li>\r\n");
      out.write("                        <li class=\"slide slide3\"></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"title\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <img src=\"./img/wedding-img4.png.webp\" alt=\"\">\r\n");
      out.write("                    <hr>\r\n");
      out.write("                    <h2>WE ARE GETTING MARRIED</h2>                        \r\n");
      out.write("                    <h3>SEPTEMBER 20TH, 2015</h3>                            \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- 좌우화살버튼 -->\r\n");
      out.write("            <a href=\"#\" class=\"arrow-next-btn\"><i></i></a>\r\n");
      out.write("            <a href=\"#\" class=\"arrow-prev-btn\"><i></i></a>\r\n");
      out.write("\r\n");
      out.write("            <!-- 인디게이트 버튼 || 페이지네이션 버튼    -->\r\n");
      out.write("            <div class=\"page-btn-box\">\r\n");
      out.write("                <span><a href=\"#\" class=\"page-btn blind\">페이지1</a></span>\r\n");
      out.write("                <span><a href=\"#\" class=\"page-btn blind\">페이지2</a></span>\r\n");
      out.write("                <span><a href=\"#\" class=\"page-btn blind\">페이지3</a></span>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <section id=\"section2\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"gap\">\r\n");
      out.write("                <div class=\"title\">\r\n");
      out.write("                    <h2>THE COUPLE</h2>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <div class=\"left\">\r\n");
      out.write("                        <div class=\"content-box\">\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li class=\"left-image\">\r\n");
      out.write("                                    <div class=\"gap\">\r\n");
      out.write("                                        <div class=\"img-box\">\r\n");
      out.write("                                            <figure>\r\n");
      out.write("                                                <img src=\"./img/wedding-img5.jpg\" alt=\"\">\r\n");
      out.write("                                            </figure>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"left-text\">\r\n");
      out.write("                                    <div class=\"gap\">\r\n");
      out.write("                                        <div class=\"text-box\">\r\n");
      out.write("                                            <ul>\r\n");
      out.write("                                                <li><h2><i class=\"fa fa-quote-left\"></i></h2></li>\r\n");
      out.write("                                                <li><h3>WE ARE SHAPED AND FASHIONED BY WHAT WE LOVE.</h3></li>\r\n");
      out.write("                                                <li><h4>I AM LAILA</h4></li>\r\n");
      out.write("                                                <li><p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the standard dummy text. Lorem Ipsum is simply dummy text.</p></li>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"icon-box\">\r\n");
      out.write("                            <div class=\"left\">\r\n");
      out.write("                                <a href=\"#\"><i class=\"fa fa-facebook-f\"></i></a>\r\n");
      out.write("                                <a href=\"#\"><i class=\"fa fa-twitter\"></i></a>\r\n");
      out.write("                                <a href=\"#\"><i class=\"fa fa-dribbble\"></i></a>\r\n");
      out.write("                                <a href=\"#\"><i class=\"fa fa-linkedin\"></i></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"right\">\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"right\">\r\n");
      out.write("                        <div class=\"content-box\">\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li class=\"left-image\">\r\n");
      out.write("                                    <div class=\"gap\">\r\n");
      out.write("                                        <div class=\"img-box\">\r\n");
      out.write("                                            <figure>\r\n");
      out.write("                                                <img src=\"./img/wedding-img6.jpg\" alt=\"\">\r\n");
      out.write("                                            </figure>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"left-text\">\r\n");
      out.write("                                    <div class=\"gap\">\r\n");
      out.write("                                        <div class=\"text-box\">\r\n");
      out.write("                                            <ul>\r\n");
      out.write("                                                <li><h2><i class=\"fa fa-quote-left\"></i></h2></li>\r\n");
      out.write("                                                <li><h3>WE ARE SHAPED AND FASHIONED BY WHAT WE LOVE.</h3></li>\r\n");
      out.write("                                                <li><h4>I AM LAILA</h4></li>\r\n");
      out.write("                                                <li><p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the standard dummy text. Lorem Ipsum is simply dummy text.</p></li>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"icon-box\">\r\n");
      out.write("                            <div class=\"left\">\r\n");
      out.write("                                <a href=\"#\"><i class=\"fa fa-facebook-f\"></i></a>\r\n");
      out.write("                                <a href=\"#\"><i class=\"fa fa-twitter\"></i></a>\r\n");
      out.write("                                <a href=\"#\"><i class=\"fa fa-dribbble\"></i></a>\r\n");
      out.write("                                <a href=\"#\"><i class=\"fa fa-linkedin\"></i></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"right\">\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <section id=\"section3\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"gap\">\r\n");
      out.write("                <div class=\"title\">\r\n");
      out.write("                    <h2>EAGERLY WAITING FOR OUR WEDDING DATE</h2>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <section id=\"section4\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"gap\">\r\n");
      out.write("                <div class=\"title\">\r\n");
      out.write("                    <h2>EVENT & PARTIES</h2>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <div class=\"col-gap\">\r\n");
      out.write("                                <div class=\"box\">\r\n");
      out.write("                                    <div class=\"gap\">\r\n");
      out.write("                                        <!-- <h2><i class=\"fa fa-ambulance\"></i></h2> -->\r\n");
      out.write("                                        <!-- <h2><i class=\"material-icons\">access_alarm</i></h2> -->\r\n");
      out.write("                                        <h2><i class=\"icon-wine\"></i></h2>\r\n");
      out.write("                                        <h3>COCKTAIL PARTY</h3>\r\n");
      out.write("                                        <hr>\r\n");
      out.write("                                        <p>SEPTEMBER 19TH, 2015</p>\r\n");
      out.write("                                        <h4>12:00 PM – 16:00 PM</h4>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <div class=\"col-gap\">\r\n");
      out.write("                                <div class=\"box\">\r\n");
      out.write("                                    <div class=\"gap\">\r\n");
      out.write("                                        <!-- <h2><i class=\"fa fa-apple\"></i></h2> -->\r\n");
      out.write("                                        <!-- <h2><i class=\"fas fa-air-freshener\"></i></h2> -->\r\n");
      out.write("                                        <h2><i class=\"icon-heart\"></i></h2>\r\n");
      out.write("                                        <h3>WEDDING CEREMONY</h3>\r\n");
      out.write("                                        <hr>\r\n");
      out.write("                                        <p>SEPTEMBER 19TH, 2015</p>\r\n");
      out.write("                                        <h4>12:00 PM – 16:00 PM</h4>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <div class=\"col-gap\">\r\n");
      out.write("                                <div class=\"box\">\r\n");
      out.write("                                    <div class=\"gap\">\r\n");
      out.write("                                        <!-- <h2><i class=\"glyphicon glyphicon-apple\"></i></h2> -->\r\n");
      out.write("                                        <h2><i class=\"icon-gift\"></i></h2>\r\n");
      out.write("                                        <h3>WEDDING PARTY</h3>\r\n");
      out.write("                                        <hr>\r\n");
      out.write("                                        <p>SEPTEMBER 19TH, 2015</p>\r\n");
      out.write("                                        <h4>18:00 PM – 07:00 AM</h4>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <section id=\"section5\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"gap\">\r\n");
      out.write("                <div class=\"title\"><h2>PHOTO GALLERY</h2></div>\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <div class=\"gallery-box\">\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <div class=\"col-gap\">\r\n");
      out.write("                                    <a href=\"#\">\r\n");
      out.write("                                        <figure>\r\n");
      out.write("                                            <img src=\"./img/wedding-img8.jpg\" alt=\"\">\r\n");
      out.write("                                        </figure>                                            \r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <div class=\"col-gap\">\r\n");
      out.write("                                    <a href=\"#\">\r\n");
      out.write("                                        <figure>\r\n");
      out.write("                                            <img src=\"./img/wedding-img9.jpg\" alt=\"\">\r\n");
      out.write("                                        </figure>                                            \r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <div class=\"col-gap\">\r\n");
      out.write("                                    <a href=\"#\">\r\n");
      out.write("                                        <figure>\r\n");
      out.write("                                            <img src=\"./img/wedding-img10.jpg\" alt=\"\">\r\n");
      out.write("                                        </figure>                                            \r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <div class=\"col-gap\">\r\n");
      out.write("                                    <a href=\"#\">\r\n");
      out.write("                                        <figure>\r\n");
      out.write("                                            <img src=\"./img/wedding-img11.jpg\" alt=\"\">\r\n");
      out.write("                                        </figure>                                            \r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <div class=\"col-gap\">\r\n");
      out.write("                                    <a href=\"#\">\r\n");
      out.write("                                        <figure>\r\n");
      out.write("                                            <img src=\"./img/wedding-img12.jpg\" alt=\"\">\r\n");
      out.write("                                        </figure>                                            \r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <div class=\"col-gap\">\r\n");
      out.write("                                    <a href=\"#\">\r\n");
      out.write("                                        <figure>\r\n");
      out.write("                                            <img src=\"./img/wedding-img13.jpg\" alt=\"\">\r\n");
      out.write("                                        </figure>                                            \r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <div class=\"col-gap\">\r\n");
      out.write("                                    <a href=\"#\">\r\n");
      out.write("                                        <figure>\r\n");
      out.write("                                            <img src=\"./img/wedding-img14.jpg\" alt=\"\">\r\n");
      out.write("                                        </figure>                                            \r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <div class=\"col-gap\">\r\n");
      out.write("                                    <a href=\"#\">\r\n");
      out.write("                                        <figure>\r\n");
      out.write("                                            <img src=\"./img/wedding-img15.jpg\" alt=\"\">\r\n");
      out.write("                                        </figure>                                            \r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <section id=\"section6\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"gap\">\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <div class=\"col-gap\">\r\n");
      out.write("                                <div class=\"content-box left\">\r\n");
      out.write("                                    <h2>\r\n");
      out.write("                                        BE PRESENT AT THE WEDDING TO GIVE YOUR BLESSINGS & LOVE.\r\n");
      out.write("                                    </h2>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <div class=\"col-gap\">\r\n");
      out.write("                                <div class=\"content-box right\">\r\n");
      out.write("                                    <div class=\"content-wrap\">\r\n");
      out.write("                                        <h2 class=\"content-head\">ARE YOU ATTENDING?</h2>\r\n");
      out.write("                                        <form name=\"message_form\" id=\"messageForm\" method=\"post\" action=\"./message.php\">\r\n");
      out.write("                                            <ul>\r\n");
      out.write("                                                <li><input type=\"text\" name=\"irum\" id=\"irum\" placeholder=\"YURE NAME\"></li>\r\n");
      out.write("                                                <li><input type=\"email\" name=\"email\" id=\"email\" placeholder=\"YURE EMAIL\"></li>\r\n");
      out.write("                                                <li>\r\n");
      out.write("                                                    <div>\r\n");
      out.write("                                                        <select name=\"select1\" id=\"select1\">\r\n");
      out.write("                                                            <option value=\"\" selected>NUMBER OF GUESTS</option>\r\n");
      out.write("                                                            <option value=\"01\">01</option>\r\n");
      out.write("                                                            <option value=\"02\">02</option>\r\n");
      out.write("                                                            <option value=\"03\">03</option>\r\n");
      out.write("                                                            <option value=\"04\">04</option>\r\n");
      out.write("                                                            <option value=\"05\">05</option>\r\n");
      out.write("                                                        </select>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div>\r\n");
      out.write("                                                        <select name=\"select2\" id=\"select2\">\r\n");
      out.write("                                                            <option value=\"ALL EVENTS\" selected>ALL EVENTS</option>\r\n");
      out.write("                                                            <option value=\"Cocktail Party\">Cocktail Party</option>\r\n");
      out.write("                                                            <option value=\"Wedding Ceremony\">Wedding Ceremony</option>\r\n");
      out.write("                                                            <option value=\"Wedding Party\">Wedding Party</option>\r\n");
      out.write("                                                        </select>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li>\r\n");
      out.write("                                                    <textarea name=\"message\" id=\"message\" placeholder=\"YURE MESSAGE\"></textarea>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li>\r\n");
      out.write("                                                    <button type=\"submit\" class=\"submit-btn\">Send Message</button>   \r\n");
      out.write("                                                </li>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("                                        </form>\r\n");
      out.write("                                        <div class=\"content-foot foot1\">Your message was sent successfully. Thanks.</div>\r\n");
      out.write("                                        <div class=\"content-foot foot2\">Validation errors occurred. Please confirm the fields and submit it again.</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <section id=\"section7\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"gap\">\r\n");
      out.write("                <div class=\"title\">\r\n");
      out.write("                    <h2>GIFT REGISTRY</h2>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s.</p>\r\n");
      out.write("                    <span>\r\n");
      out.write("                        <a href=\"#\"><img src=\"./img/wedding-img18.jpg\" alt=\"\"></a>\r\n");
      out.write("                        <a href=\"#\"><img src=\"./img/wedding-img19.jpg\" alt=\"\"></a>\r\n");
      out.write("                        <a href=\"#\"><img src=\"./img/wedding-img20.jpg\" alt=\"\"></a>\r\n");
      out.write("                        <a href=\"#\"><img src=\"./img/wedding-img21.jpg\" alt=\"\"></a>\r\n");
      out.write("                    </span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <section id=\"section8\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"gap\">\r\n");
      out.write("                <div class=\"title\">\r\n");
      out.write("                    <h2>OUR STORY</h2>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <div class=\"slide-container\">\r\n");
      out.write("                        <div class=\"slide-view\">\r\n");
      out.write("                            <ul class=\"slide-wrap\">\r\n");
      out.write("                                <li class=\"slide slide1\">\r\n");
      out.write("                                    <div class=\"col-gap\">\r\n");
      out.write("                                        <div class=\"top-box\">\r\n");
      out.write("                                            <img src=\"./img/wedding-img8.jpg\" alt=\"\">\r\n");
      out.write("                                            <span>\r\n");
      out.write("                                                <em>30 March 2016</em>\r\n");
      out.write("                                            </span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"bottom-box\">\r\n");
      out.write("                                            <h3>01</h3>\r\n");
      out.write("                                            <div>\r\n");
      out.write("                                                <h4>Our First Dating</h4>\r\n");
      out.write("                                                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry....</p>\r\n");
      out.write("                                                <i></i>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"slide slide1\">\r\n");
      out.write("                                    <div class=\"col-gap\">\r\n");
      out.write("                                        <div class=\"top-box\">\r\n");
      out.write("                                            <img src=\"./img/wedding-img9.jpg\" alt=\"\">\r\n");
      out.write("                                            <span>\r\n");
      out.write("                                                <em>30 March 2016</em>\r\n");
      out.write("                                            </span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"bottom-box\">\r\n");
      out.write("                                            <h3>02</h3>\r\n");
      out.write("                                            <div>\r\n");
      out.write("                                                <h4>Our First Dating</h4>\r\n");
      out.write("                                                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry....</p>\r\n");
      out.write("                                                <i></i>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"slide slide1\">\r\n");
      out.write("                                    <div class=\"col-gap\">\r\n");
      out.write("                                        <div class=\"top-box\">\r\n");
      out.write("                                            <img src=\"./img/wedding-img10.jpg\" alt=\"\">\r\n");
      out.write("                                            <span>\r\n");
      out.write("                                                <em>30 March 2016</em>\r\n");
      out.write("                                            </span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"bottom-box\">\r\n");
      out.write("                                            <h3>03</h3>\r\n");
      out.write("                                            <div>\r\n");
      out.write("                                                <h4>Our First Dating</h4>\r\n");
      out.write("                                                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry....</p>\r\n");
      out.write("                                                <i></i>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"slide slide1\">\r\n");
      out.write("                                    <div class=\"col-gap\">\r\n");
      out.write("                                        <div class=\"top-box\">\r\n");
      out.write("                                            <img src=\"./img/wedding-img11.jpg\" alt=\"\">\r\n");
      out.write("                                            <span>\r\n");
      out.write("                                                <em>30 March 2016</em>\r\n");
      out.write("                                            </span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"bottom-box\">\r\n");
      out.write("                                            <h3>04</h3>\r\n");
      out.write("                                            <div>\r\n");
      out.write("                                                <h4>Our First Dating</h4>\r\n");
      out.write("                                                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry....</p>\r\n");
      out.write("                                                <i></i>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"slide slide1\">\r\n");
      out.write("                                    <div class=\"col-gap\">\r\n");
      out.write("                                        <div class=\"top-box\">\r\n");
      out.write("                                            <img src=\"./img/wedding-img12.jpg\" alt=\"\">\r\n");
      out.write("                                            <span>\r\n");
      out.write("                                                <em>30 March 2016</em>\r\n");
      out.write("                                            </span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"bottom-box\">\r\n");
      out.write("                                            <h3>05</h3>\r\n");
      out.write("                                            <div>\r\n");
      out.write("                                                <h4>Our First Dating</h4>\r\n");
      out.write("                                                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry....</p>\r\n");
      out.write("                                                <i></i>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>                                    \r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <section id=\"section9\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"gap\">\r\n");
      out.write("                <div class=\"title\">\r\n");
      out.write("                    <h2>RECENT BLOG</h2>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <div class=\"col-gap\">\r\n");
      out.write("                                <div class=\"img-box\">\r\n");
      out.write("                                    <img src=\"./img/wedding-img22.jpg\" alt=\"\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"txt-box\">\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li><a href=\"#\">WEDDING</a></li>\r\n");
      out.write("                                        <li><h3><a href=\"#\">WEDDINGS ARE IMPORTANT BECAUSE THEY CELEBRATE LIFE AND POSSIBILITY.</a></h3></li>\r\n");
      out.write("                                        <li><p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum is...</p></li>\r\n");
      out.write("                                        <li><hr></li>\r\n");
      out.write("                                        <li><a href=\"#\">JUNE 30, 2016</a> / POSTED BY <a href=\"#\">HARESH</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <div class=\"col-gap\">\r\n");
      out.write("                                <div class=\"img-box\">\r\n");
      out.write("                                    <img src=\"./img/wedding-img23.jpg\" alt=\"\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"txt-box\">\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li><a href=\"#\">WEDDING</a></li>\r\n");
      out.write("                                        <li><h3><a href=\"#\">A WOMAN WITH A FINE PROSPECT OF HAPPINESS BEHIND HER.</a></h3></li>\r\n");
      out.write("                                        <li><p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum is...</p></li>\r\n");
      out.write("                                        <li><hr></li>\r\n");
      out.write("                                        <li><a href=\"#\">JUNE 30, 2016</a> / POSTED BY <a href=\"#\">HARESH</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <div class=\"col-gap\">\r\n");
      out.write("                                <div class=\"img-box\">\r\n");
      out.write("                                    <img src=\"./img/wedding-img24.jpg\" alt=\"\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"txt-box\">\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li><a href=\"#\">WEDDING</a></li>\r\n");
      out.write("                                        <li><h3><a href=\"#\">I WAS MARRIED BY A JUDGE. I SHOULD HAVE ASKED FOR A JURY.</a></h3></li>\r\n");
      out.write("                                        <li><p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum is...</p></li>\r\n");
      out.write("                                        <li><hr></li>\r\n");
      out.write("                                        <li><a href=\"#\">JUNE 30, 2016</a> / POSTED BY <a href=\"#\">HARESH</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <section id=\"section10\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"gap\">\r\n");
      out.write("                <div class=\"title\">\r\n");
      out.write("                    <h2>LOCATION</h2>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <section id=\"section11\">\r\n");
      out.write("        <iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3158.230064012958!2d126.75852181564994!3d37.667301526107906!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x357c855df4876fe3%3A0xecb41ce28340f76!2z6rOg7JaR7IucIOyjvOyXvTHrj5kgMTQwOCDqsJXshKDrp4jsnYTrkZDsgrAxNOuLqOyngOyVhO2MjO2KuA!5e0!3m2!1sko!2skr!4v1675237256606!5m2!1sko!2skr\" allowfullscreen=\"\" loading=\"lazy\" referrerpolicy=\"no-referrer-when-downgrade\"></iframe>\r\n");
      out.write("    </section>\r\n");
      out.write("</main>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
