/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-07-19 02:36:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import kurly.UserDAO;
import kurly.UserDTO;
import java.util.*;

public final class kurly_005fuser_005fmain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("kurly.UserDTO");
    _jspx_imports_classes.add("kurly.UserDAO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./public/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"wrap\">\r\n");
      out.write("    <section id=\"signup\" class=\"main\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"title\">\r\n");
      out.write("                <h2>메인 페이지</h2>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            ");

                // 2. 회원가입 페이지에서 가입된 화면처리하기
                //    로그인 유지 회원아이디 변수에 넣어준다.
                String loginId = null;
                if( session.getAttribute("user_id") != null ){ // 세션설정된 값 가져오기
                    loginId  = (String) session.getAttribute("user_id");
                }

                if(loginId == null){
            
      out.write("\r\n");
      out.write("                    <div class=\"content\">\r\n");
      out.write("                    <h3>접속하기</h3>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"./kurly_user_signin.jsp\">로그인</a></li>\r\n");
      out.write("                            <li><a href=\"./kurly_user_signup.jsp\">회원가입</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("            ");

                }
                else{    
            
      out.write("\r\n");
      out.write("                    <div class=\"content\">\r\n");
      out.write("                        <h3>회원관리</h3>\r\n");
      out.write("                        <h4>회원 [");
      out.print( loginId );
      out.write("]님</h4>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"./kurly_user_update.jsp\">개인정보수정</a></li>\r\n");
      out.write("                            <li><a href=\"./kurly_user_delete.jsp\">회원탈퇴</a></li>\r\n");
      out.write("                            <li><a href=\"./kurly_user_logout.jsp\">로그아웃</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("              \r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <div class=\"get-join-list\">\r\n");
      out.write("\r\n");
      out.write("                    <table>\r\n");
      out.write("                        <caption>회원 LIST 목록</caption>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th>아이디</th>\r\n");
      out.write("                            <th>비밀번호</th>\r\n");
      out.write("                            <th>이름</th>\r\n");
      out.write("                            <th>이메일</th>\r\n");
      out.write("                            <th>휴대폰</th>\r\n");
      out.write("                            <th>주소</th>\r\n");
      out.write("                            <th>성별</th>   \r\n");
      out.write("                            <th>생년월일</th>\r\n");
      out.write("                            <th>가입일</th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        ");

                            UserDAO userDAO = new UserDAO();
                            List<UserDTO> list = new ArrayList<>();
                            list = userDAO.getJoinList();

                            if(list.size()==0){
                                out.println("<script>alert('조회내역이 없습니다.');</script>");
                            }
                            else{
                                    for(UserDTO item : list){
                        
      out.write("        \r\n");
      out.write("\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <td>");
      out.print( item.getUser_id() );
      out.write("</td>\r\n");
      out.write("                                        <td>");
      out.print( item.getUser_pw() );
      out.write("</td>\r\n");
      out.write("                                        <td>");
      out.print( item.getUser_name() );
      out.write("</td>\r\n");
      out.write("                                        <td>");
      out.print( item.getUser_email() );
      out.write("</td>\r\n");
      out.write("                                        <td>");
      out.print( item.getUser_ph() );
      out.write("</td>\r\n");
      out.write("                                        <td>");
      out.print( item.getUser_address() );
      out.write("</td>\r\n");
      out.write("                                        <td>");
      out.print( item.getUser_gender() );
      out.write("</td>\r\n");
      out.write("                                        <td>");
      out.print( item.getUser_birth() );
      out.write("</td>\r\n");
      out.write("                                                         \r\n");
      out.write("                                    </tr>\r\n");
      out.write("\r\n");
      out.write("                        ");

                                    }
                            }
                        
      out.write("\r\n");
      out.write("                            </table>\r\n");
      out.write("\r\n");
      out.write("            ");

                }
            
      out.write("  \r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("           \r\n");
      out.write("    </section>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
